version: '3.8'
services:
  mysql:
    container_name: mysql
    build: ./db
    image: inaserul/trio-db:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: flask-db
    volumes:
    - type: volume
      source: trio-mysql
      target: /var/lib/mysql
  flask-app:
    container_name: flask-app
    build: ./flask-app
    image: inaserul/trio-flask-app:latest
    environment:
      DATABASE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    deploy:
      replicas: 4
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  nginx:
    container_name: nginx
    image: nginx:latest
    deploy:
      replicas: 4
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
volumes:
  trio-mysql:
    external: false
