version: '3.7'
services:
  mysql:
    container_name: mysql
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: flask-db
  flask-app:
    build: ./flask-app
    environment:
      DATABASE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf